"""Domain-disjoint data generated by the actual MuJoCo engine."""
import argparse
from concurrent.futures import ProcessPoolExecutor
import hashlib
import json
from pathlib import Path
import time
import numpy as np
from .environment import Plant, sample_domain, reference, geometric, DT, SCENE
from .experiment import digest, require_x_artifact


def domain_data(args):
    split, seed, episodes, steps, headings = args
    domain = sample_domain(seed, split)
    plant, rng = Plant(domain), np.random.default_rng(seed)
    states, actions, snapshots, contacts = [], [], [], 0
    for episode in range(episodes):
        kind = ["hover", "circle", "figure8", "figure8"][episode%4]
        heading = headings[episode%len(headings)]
        radius, period, phase = rng.uniform(.7, 2.2), rng.uniform(8, 15), rng.uniform(0, 10)
        initial = reference(phase, kind, radius, period, heading=heading)[0]
        initial[:3] += rng.normal(0, .10, 3)
        initial[3:6] += rng.normal(0, .15, 3)
        plant.reset(initial)
        ss, aa, qq, noise = [], [], [], np.zeros(4)
        for step in range(steps):
            state = plant.state()
            target, acc = reference(phase+step*DT, kind, radius, period, heading=heading)
            # Temporally correlated motor excitation, shared across model arms.
            noise = .65*noise+rng.normal(0, .09 if episode%4 == 0 else .16, 4)
            action = np.clip(geometric(state, target, acc, plant.trim)+noise, 0, 12)
            ss.append(state); aa.append(action); qq.append(plant.snapshot())
            _, contact = plant.step(action); contacts += int(contact)
        ss.append(plant.state()); qq.append(plant.snapshot())
        states.append(ss); actions.append(aa); snapshots.append(qq)
    return split, seed, domain.json(), np.asarray(states, np.float32), np.asarray(actions, np.float32), np.asarray(snapshots), contacts


def main():
    p = argparse.ArgumentParser(); p.add_argument("--output", type=Path, required=True); p.add_argument("--protocol", type=Path, required=True)
    a = p.parse_args(); protocol = json.loads(a.protocol.read_text())
    require_x_artifact(protocol)
    a.output.mkdir(parents=True, exist_ok=False)
    tasks = [(split, protocol["domain_seeds"][split]+i, protocol["episodes_per_domain"], protocol["episode_steps"], protocol.get("heading_modes", ["fixed"]))
             for split, n in protocol["domains"].items() for i in range(n)]
    metadata, arrays, start = [], {}, time.monotonic()
    with ProcessPoolExecutor(max_workers=6) as pool:
        for split, seed, domain, s, u, q, contacts in pool.map(domain_data, tasks):
            arrays.setdefault(split, []).append((s, u, q, seed))
            metadata.append({"split": split, "seed": seed, "domain": domain, "contact_steps": contacts})
            print(json.dumps({"domain": seed, "split": split, "contacts": contacts, "elapsed": round(time.monotonic()-start, 1)}), flush=True)
    for split, values in arrays.items():
        np.savez_compressed(a.output/f"{split}.npz", states=np.concatenate([v[0] for v in values]),
                            actions=np.concatenate([v[1] for v in values]), snapshots=np.concatenate([v[2] for v in values]),
                            domains=np.concatenate([np.full(len(v[0]), v[3]) for v in values]),
                            headings=np.tile([protocol.get("heading_modes", ["fixed"])[j%len(protocol.get("heading_modes", ["fixed"]))] for j in range(protocol["episodes_per_domain"])], len(values)))
    train = np.load(a.output/"train.npz")
    norm = {"state_mean": train["states"].reshape(-1, 18).mean(0).tolist(),
            "state_std": np.maximum(train["states"].reshape(-1, 18).std(0), .05).tolist(),
            "action_mean": train["actions"].reshape(-1, 4).mean(0).tolist(),
            "action_std": np.maximum(train["actions"].reshape(-1, 4).std(0), .1).tolist()}
    manifest = {"domains": metadata, "normalization": norm, "heading_modes": protocol.get("heading_modes", ["fixed"]), "elapsed_seconds": time.monotonic()-start,
                "airframe": "x", "scene_sha256": digest(SCENE), "protocol_sha256": digest(a.protocol),
                "files": {f.name: hashlib.sha256(f.read_bytes()).hexdigest() for f in a.output.glob("*.npz")}}
    (a.output/"manifest.json").write_text(json.dumps(manifest, indent=2))


if __name__ == "__main__": main()
